# Generated by Django 2.2.9 on 2020-01-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('LO', 'low'), ('MD', 'medium'), ('HI', 'high')], default='HI', max_length=2),
        ),
    ]
